# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140608211457");
user_pref("browser.showQuitWarning", true);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("datareporting.healthreport.currentDaySubmissionFailureCount", 1);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1411666140285");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1411667040303");
user_pref("datareporting.healthreport.pendingDeleteRemoteData", true);
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.firstRunTime", "1411665580778");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 618);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 731);
user_pref("datareporting.sessions.current.startTime", "1411666397347");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1411665580553,\"a\":0,\"t\":0,\"c\":false,\"m\":31,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1411665700013,\"a\":2,\"t\":9,\"c\":true,\"m\":20,\"fp\":615,\"sr\":706}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1411666083162,\"a\":6,\"t\":38,\"c\":true,\"m\":31,\"fp\":684,\"sr\":774}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1411666121831,\"a\":7,\"t\":34,\"c\":true,\"m\":1,\"fp\":599,\"sr\":706}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1411666157236,\"a\":0,\"t\":5,\"c\":false,\"m\":31,\"fp\":609,\"sr\":705}");
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-fr@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-fr@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\",\"mtime\":1385484250000,\"rdfTime\":1336770080000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1402264734000},\"langpack-fr@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-fr@firefox.mozilla.org.xpi\",\"mtime\":1402264755000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1402264735000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1404133877000,\"rdfTime\":1402263466000},\"mint-search-enhancer@linuxmint.com\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/mint-search-enhancer@linuxmint.com\",\"mtime\":1385484249000,\"rdfTime\":1336764609000}}}]");
user_pref("extensions.lastAppVersion", "30.0");
user_pref("extensions.lastPlatformVersion", "30.0");
user_pref("gecko.buildID", "20140608211457");
user_pref("gecko.mstone", "30.0");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1411666397);
user_pref("toolkit.telemetry.previousBuildID", "20140608211457");
