#!/bin/sh
while true; do

    # Clean up previously running apps, gracefully at first then harshly
    sleep 2
    pkill -SIGKILL -f firefox 2>/dev/null
    pkill -SIGKILL -f matchbox-window-manager 2>/dev/null
    sleep 2

    # Clean out existing profile information
    rm -rf /home/pi/.mozilla

    # Bring in the bare minimum to keep Firefox happy
    cp -r /boot/.mozilla /home/pi/

    # Disable DPMS / Screen blanking
    xset -dpms
    xset s off

    # Reset the framebuffer's colour-depth
    fbset -depth $( cat /sys/module/*fb*/parameters/fbdepth );

    # Hide the cursor (move it to the bottom-right, comment out if you want mouse interaction)
    xwit -root -warp $( cat /sys/module/*fb*/parameters/fbwidth ) $( cat /sys/module/*fb*/parameters/fbheight )

    # Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
    matchbox-window-manager -use_titlebar no -use_cursor no &

    # Start the browser (See http://peter.sh/experiments/chromium-command-line-switches/)
    firefox

done;

